server:
  port: 8080

spring:
  datasource:
    username: narc
    password: 1234
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: com.dao.entity

