server:
  port: 8080

spring:
  datasource:
    username: narc
    password: 1234
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapping/*Mapper*.xml
  type-aliases-package: com.entity

